import { Line } from 'react-chartjs-2';
import {
    Chart as ChartJS, CategoryScale, LinearScale, PointElement, LineElement, Title, Tooltip, Legend, Filler
} from 'chart.js';

ChartJS.register(CategoryScale, LinearScale, PointElement, LineElement, Title, Tooltip, Legend, Filler);

// Converts a solid hex code (e.g., '#ff003c') into a transparent rgba for the chart fill
// Rather than hardcoding RGBA values, colours can be generated dynamically based on the active color, ensuring perfect harmony between the line and its fill regardless of which metric is selected, or colour is used.
const hexToRgba = (hex, alpha) => {
    const r = parseInt(hex.slice(1, 3), 16);
    const g = parseInt(hex.slice(3, 5), 16);
    const b = parseInt(hex.slice(5, 7), 16);
    return `rgba(${r}, ${g}, ${b}, ${alpha})`;
};

// ActiveColor is passed from the parent and represents the color associated with the currently selected metric (e.g., Calories might be cyan, Protein might be red). This allows the line graph to dynamically change its color scheme to match the active metric. The activeColor is used both for the line itself and as a base for generating a lighter fill color, ensuring that the graph remains visually consistent and appealing regardless of which metric is being displayed.
const LineGraph = ({ historicalData, activeMetric, activeColor }) => {
    if (!historicalData || historicalData.length === 0) {
        return (
            <div style={{ color: '#666', textAlign: 'center', paddingTop: '100px', fontFamily: '"Courier New", monospace' }}>
                No data available to display. Start comparing foods to see your nutrient history here!
            </div>
        );
    }

    // CHART CONFIGURATION
    const options = {
        responsive: true, maintainAspectRatio: false,
        plugins: {
            legend: { display: false }, title: { display: false },
            tooltip: {
                backgroundColor: 'rgba(10, 10, 10, 0.9)', titleFont: { family: '"Courier New", monospace', size: 14 },
                bodyFont: { family: '"Courier New", monospace', size: 14 }, borderColor: '#333', borderWidth: 1, padding: 12, displayColors: false,
                callbacks: { label: (context) => `${context.raw} ${activeMetric === 'Calories' ? 'kcal' : 'g'}` }
            }
        },
        scales: {
            x: { grid: { color: 'rgba(255, 255, 255, 0.05)' }, ticks: { color: '#888', font: { family: '"Courier New", monospace', size: 11 } } },
            y: { grid: { color: 'rgba(255, 255, 255, 0.05)' }, ticks: { color: '#888', font: { family: '"Courier New", monospace' } }, beginAtZero: true }
        }
    };

    // The data object is constructed by mapping over the historicalData array, extracting the relevant metric values for each food item. The labels are set to the names of the food items, and the dataset contains the values for the active metric. The line color is set to activeColor, while the background color for the fill is generated by converting activeColor to an RGBA value with 10% opacity using the hexToRgba function. This dynamic approach makes sure that the graph's colors are always in sync with the selected metric.
    const data = {
        labels: historicalData.map(item => item.name),
        datasets: [
            {
                label: `${activeMetric} per 100g`,
                data: historicalData.map(item => item[activeMetric]),
                // Applying the color from the parent
                borderColor: activeColor,
                backgroundColor: hexToRgba(activeColor, 0.1), // 10% opacity for the wave glow
                borderWidth: 3,
                pointBackgroundColor: '#0a0a0a',
                pointBorderColor: activeColor,
                pointBorderWidth: 2,
                pointRadius: 5,
                fill: true,
                tension: 0.4
            }
        ]
    };

    return <Line options={options} data={data} />;
};

export default LineGraph;